/**
 * Strip out non-alphanumeric characters and remove the trailing "s" or "ing"
 *
 * @param {string} str
 * @returns {string}
 */
function normalize(str) {
  return str
    .toLowerCase()
    .replace(/[^a-z0-9]/g, "")
    .replace(/(s|ing)$/, "");
}

/**
 * Determine whether the search value matches the keywords
 *
 * @param {string} keywords
 * @param {string} search
 * @returns {boolean}
 */
function findMatch(keywords, search) {
  const normalizedSearch = search.split(/ +/).map(normalize);
  const normalizedKeywords = keywords.split(/, +/).map(normalize);
  return [...normalizedSearch].every((word) =>
    normalizedKeywords.some((k) => k.startsWith(word))
  );
}

/**
 * Strip the prefix from the icon URL to get the icon ID
 *
 * @param {string} iconURL
 * @returns {*}
 */
function getIconID(iconURL) {
  return iconURL.replace("https://card-content.yotoplay.com/icons/", "");
}

/**
 * Hide icons that don't match the search value
 *
 * @param {string} searchValue
 */
function filterIcons(searchValue) {
  const icons = document.querySelectorAll(
    ":not([aria-hidden=true]) #simple-tabpanel-0 .trackIcon"
  );
  icons.forEach((icon) => {
    const iconID = getIconID(icon.src);
    const keywords = KEYWORD_MAP[iconID];

    const parent = icon.parentElement;
    if (searchValue === "") {
      parent.classList.remove("hidden");
      return;
    }
    if (findMatch(keywords, searchValue)) {
      parent.classList.remove("hidden");
    } else {
      parent.classList.add("hidden");
    }
  });
}

function addAltTextToIcons() {
  const icons = document.querySelectorAll(
    ":not([aria-hidden=true]) #simple-tabpanel-0 .trackIcon"
  );
  icons.forEach((icon) => {
    const iconID = getIconID(icon.src);
    const keywords = keywordMap[iconID];
    if (keywords) {
      icon.alt = keywords;
      icon.title = keywords;
    }
  });
}

/**
 * Make sure the search bar exists and put the alt text on the icons
 */
function ensureSearch() {
  const search = document.querySelector("#icon-search-ext input");
  addAltTextToIcons();
  if (search) {
    return search;
  }
  const html = `
<div id="icon-search-ext">
  <input type="search" placeholder="Search for an icon" autofocus />
</div>
`;

  const doc = new DOMParser().parseFromString(
    html,
    "text/html"
  ).firstElementChild;

  const searchBar = doc.querySelector("input");
  searchBar.dataset.testid = "icon-search";
  searchBar.addEventListener("input", (e) => {
    filterIcons(e.currentTarget.value);
  });

  const tabPanel = document.querySelector(
    `:not([aria-hidden=true]) #simple-tabpanel-0`
  );
  if (tabPanel) {
    tabPanel.prepend(doc);
  } else {
    console.log("No tab panel found");
  }
}

var mutationObserver = new MutationObserver(function () {
  ensureSearch();
});

mutationObserver.observe(document.body, {
  childList: true,
  subtree: true,
});

// prettier-ignore
/**
 * Map from icon ID to keywords
 *
 * @type {Record<string, string>}
 */
const KEYWORD_MAP = {
  "_WWpLHoOj6iqeREcGkJnGlsis2QSF6znM0UPFdXTjf8": "music, note, sing, song, sound",
  "GFz47I4ONd5w_4F1_6QDE7RgMpCi0emxaoHDsB2Ag_s": "police, man, policeman, person, human",
  "KRqb3_ettklXTWCSfpYOjr7FB3kvwjaGzydYnZDjgyw": "lion, animal",
  "TIqkee2shZStGLOqvHOuakWsJb6ra2GD_mMR2SoBCGw": "chicken, rooster, hen, bird, animal",
  "-Z6XuGzfAKy7_qyL3l9gTejVNQkTfejgJHLQDmspvSE": "baby, kid, boy",
  "RVigEzrtqt6pPT8Mp9ZBppeM4FoX1yX-sv0JRFZeJ-s": "hat, safari",
  "mTPUPQwM_T6FUzX7CvtYASo3cGN6zOPM9zXAZO2uqas": "fairy, princess, girl, woman, magic",
  "gCgNJrpHZ186Hd1ttD-k0R2Cf38FbPW3riwe27WAiJA": "star, twinkle",
  "PWf5lBShHueq-q9dSqG_NVz3R-f8FTmtlnJY5hpPFyw": "man, black",
  "ojsuXV9Ap9rItp25p1zQPz2q0aUBzLBLWNomG25cVeo": "woman, black",
  "AC6ySygbay79fIMHmMtYN9ekBo1kwMvRoi4DQW_CZW0": "pirate, man",
  "1vqi7TbtDFUTSxI_oGbV7pzdxmo8mQfNkF28oejlhuE": "snowman, snow, winter, holiday",
  "5pjWyPe51YQDhjDb_aUMbWnEIb1cDJirmEIjuB2VPYs": "point, hand",
  "WsZrlAbVYAVX0yWYXsveVolBAaRZmsAVx2GaQiMpuas": "bike, motorcycle, vehicle",
  "Qvr52DzMayjEdD7hPSgBcTY1LXRgxbxWZi__1Npgurc": "girl, cry, sad",
  "0Okwjjy22fAbLtmGls6144g_YunzEAvXCUg4ozzn32Q": "soccer, ball, soccerball, sports",
  "tNXOIzQIPO6OjSzmT5WFofHhK3-KRGYvnlBxE1oF0-4": "tada, celebrate, party, happy",
  "VH4rf7ab6852014Dicc-X268W34q98piqnTaHpnpX0w": "world, earth, globe, planet",
  "ATQcvMQNXZaJehk7c8vDdplIz-g-DwPfsqcZOvX6YcU": "fish, rod, animal, ",
  "Fdbn0JIzPAMMR0c4WI4hwpnHUs4uLJAbXcQIJqiUDSQ": "detective, man",
  "PTX7YQxZa_pZ6BDMyxdtzjhFkgoXSIsMCda2o9HbKA0": "sushi, food, japan",
  "_wSKyzGaQUwwrkcegv03KoDWNt1epmDbVziMISim9Kc": "penguin, bird, animal",
  "lA1wfyk72tPC1-9hcgtgQYNELkaeLA2PkK1VAqeT5gI": "joy, laugh, cry, happy, sad, emotion",
  "sL1t6wVOAhYLng93doVmxW5Z9VpzZt2rNwlXKulGQk0": "banana, fruit, food",
  "Ct24yM7BkE7ggWD73eYsgjhNOH8_eVsC9LB89mqeUEo": "sock, clothing, clothes, foot",
  "P6waZIbCze3uSp1Gw9J3SIqQWXlbBMgC19C71EAFH6A": "helicopter, fly, vehicle",
  "LVM4Uz4DZJRUV2PPwieh18i5-zaTcRHbD5fQ_wRnSNs": "football, ball, sports",
  "3ZnJD74DawVPKntS3pIEpDlM57daHtDuczmf2JI_EBw": "fire, flame, burn, hot, heat",
  "IhcTMq5Xv1W4rO6UVgQPFJ8GeXwwM9m0V_QdaEuRXDo": "plane, airplane, fly, vehicle",
  "zoSnzxNNkdIlP2KvKGjZMTuLT68RBj9J6xoQ7mtfncs": "flower, plant",
  "zIeHMsgOWq6VPfHDXK7PPOxsDjD9rxsxY9U4AKLCUwc": "ice cream, food, dessert",
  "ClikAQb6MuOV8epgyzoBYrDKZd8QR66XE4ZWH5XOns8": "princess, crown, girl, woman",
  "ZpMNxXD3HAi3bAdGUy02s8l7TFvKZZWhvLxh7xdEhXw": "woman, girl, happy, smile",
  "AjJaUh665wfnb72_y5uQ3M0w3JtobwIVfGua_A_j6i8": "moon, planet, night",
  "wXYmV3Zemj8Ge98prjh4e4R1aPnZMoi1nEkoRme3qWI": "boy, happy, smile",
  "wzzGV1tyo7mRcpgXSvAyRgQ91_zP9pjmqf0XfhOPciQ": "school, schoolbus, bus, vehicle, travel",
  "2U38u-iUK8k1mREbfUM-IGl4pw76KxLGftzHoZNOCMs": "boy, blonde, person",
  "Dw6-IJ8OYAOSzDt5ic_PCBq7AEOBZkuay7iAAnOHfFY": "woman, whistle, blow, girl, person",
  "CptcXfSeS3BEkRFkIdORpo1VNw6VQbz4mNj6KLcBkiE": "mouse, animal",
  "ugfvEHiF6efk_jU_Gsd8thDsqp62KH6ZMgUqp0Vk02o": "pizza, food",
  "y1gyQr-7MmpMTigxMprUIzJePGsCKDnpGCDfKhBGGgU": "bunny, rabbit, animal, cute",
  "UFUzOnxiDNeAOIHYfLwBLE4CLXiV_22rQKatrVN9cTg": "bread, toast, loaf, food",
  "qnca9GqlsUMBT8zpM4nvKsTnWjczYbve_xnSZfMUSoQ": "alligator, lizard, reptile, animal",
  "wLGDXvKH-YhnxpO5N8mHqZYHlE8wRhh9Ob9rTD2ks3c": "elephant, big, animal",
  "jB1P8kIw-Fkd7XO5Q0ZzkO8J8UW81Wbm0o013thJJg4": "chicken, rooster, hen, bird, animal",
  "gTMbacpoeSMYqc9fNLJnxPjylraNG6jIrYEWevyzYbA": "book, read, study, learn, school",
  "66sQh15-nQ56BTHF-7DxLlx79h7V3xBrlqvVdWW1IMQ": "frog, reptile, head, animal",
  "uiqaZz3Q_kM359pgiMaIkK-grc19uo4tRK5bSAMro7o": "book, open, read, study, learn, school",
  "JLTJueAzxOwxWJkmcLQWfAUJttJC05BbSU2WfRIutCk": "world, earth, globe, planet",
  "sa0N47sAq5txEBxBM2HrN28rVfjvnFsUKiuuN9CQiRc": "castle, building, mansion, house",
  "R-60m21dr9Al8KQCy79k7lScYFRBBCvyYRbIZSDN_0Y": "cardinal, red, bird, animal",
  "48PqNbRnn9RO8wTMjd1wkBGK4Yuo0WDQTQTlVyy-MJY": "bear, teddy, animal",
  "20l1LZ7sLHHek_2Si4XjinmKNO8ljMc5ciQozbGpKvs": "octopus, underwater, animal",
  "2A0Z4w8rZ-_IQhvH462o5yqA_5qeYZz-3MEjW4lBFxk": "pyjama, pj, dress, purple, clothing, clothes,",
  "feD4F6Xi19d9HF4rEwWtkYeC655CtcHcDA0Ib5UcgNQ": "music, note, sing, song, sound",
  "8YlAiv--FkCuz6pz3GkaZm0B9b1NBbSM_ZEByl0X14E": "woman, smile, girl, person",
  "FwbvFxkcV9eFB1OaGN2G3mUH2Rs3qcd-hHLpfZ1qwhU": "grimace, yikes, face, emotion",
  "3hauXhhWEzTn-gWMufk2-hfm6jD_ZfV8VuTu0Ep_oaQ": "tongue, face, emotion",
  "bXAXGUuG1XkGsMVBEU78kcelQ4tVZf-1wCPiEzyZ7EU": "surprise, wow, blow, face, emotion",
  "GAvCuUCyEJhyYiZ6fJFfIBHkyblyHBvTlhsz4UantDM": "moon, night, crescent",
  "xB-_hVJTrC3LveHDCr2S1CbPN92QcdSriZh2YI1_ZUA": "family, group, people, human",
  "Jk-qcwt8yYnnABZzy9WDszRfM0QX9XG5Bq3gcLLaFe4": "old, grandma, grandpa, person, human",
  "qKst1_CCXVXcKa1J-aseabnbs-cVx2crmHG13jbHrY4": "old, grandpa, mustache, person, human",
  "sTrQobnhkzioJzmUmyhGiMJc1edh0Y9yQGrx21UnaTk": "mask, face, emotion, drama",
  "fl79Xm88M5Qrl0uPtjNHRY1ZLoejWPvo8w0X_dKrqn0": "apple, fruit, food",
  "BOM4R1mz-eCN48ByNJ_qvkYtMX71WxEpfLVQH0LmahQ": "nose, body",
  "tV9oErJz52FBaywOw_IYC5uc-ZGGjqV2bz1w9m6haTA": "earth, planet, globe, world",
  "Ae-q7oOsZ3kQcpr1SH04qc-Ubc-b8ceokiCL2nI3hh4": "corn, vegetable, food",
  "OKnwRNph9SJOpgiEBppyz1mZ9xvlaZ4rbQ4_mugf3ss": "bow, red, ribbon, clothing, clothes",
  "Fcg9fEJJVJmmXPfyKxsRIL0MQ5uRzsbI9oJ2yuzNZ0s": "paint, art, brush, color",
  "4XwGfL413YcxFXsE328R_U7ZlXw03xAn6QqAKrLpZCo": "couple, friend, people, human, hold hands",
  "ipgm6iq-23ZwaOj8t-69Pmc1SIf2WFMbKBr-OmkWWVc": "stop, sign, stopsign, building, bus stop, apartment",
  "LCBoQM5qDDHBwPWdP1SM55hDvMu06-DRLod3Le5k1a0": "chocolate, treat, dessert, food",
  "o_zZFXh6IBYDwiT_0ptAPvkVycZF0uy5srYo16TjyAU": "clap, hands, applause",
  "SNrQLCmUE9h4ZnYsa-ao141NMPAsYaSQcLU6IfdK72A": "lemon, citrus, fruit, food",
  "JXgEjXOt3lyFFfzq6DpTUy0iv6EZDlofIAQHqDIoNwE": "man, woman, person, black, human",
  "Ot1JPj137ACUmzMHP_HrlunQSSlGxgKDDKU8F03fKMg": "orange, citrus, fruit, food",
  "rHe3irfzAJDE1Xpuau9gT8K2Vr2v4iNWKKSGaG6kNkM": "sunglasses, glasses, face, emotion",
  "H4Anu8Rdew0UbuQ3UitLTyFiRaKvAOKJ-mAJpL8X-hU": "tongue, body",
  "CfeVWoQtDUMnxmlOJ8_0TfqlkFsjDtGZZrsVb5A08RI": "smile, happy, face, emotion",
  "PmzIKw4R_mdKzgbIN-Mi8JENzohmrQ0OavnGURj7w_o": "ambulance, vehicle, hospital, emergency",
  "AnKy11MQUYBPjOm8DqkyhGRy1Xat3MvDXEjoGoAx7aI": "shy, embarrassed, smile, blush, face, emotion",
  "VCipqGhZiCIBI_tky0ppmM4rHw3TMCavzQbi8XO6dKM": "sun, summer, hot, bright",
  "R121TbhG9wRgnCyNQ7EkYOtz5s89IpAmXo5v2OsIE3I": "cake, birthday, candles, dessert, food",
  "4CCeXavf788GjQn0oUB_4H7oLNCFmm7v7SCDtMi1l20": "envelope, mail, letter, send",
  "0xzqHPN5ixUdh_eyf7g-FsY1Rr_uCftwnzlVGLu1p3A": "truck, shipping, vehicle",
  "X0K1eUV41nY1C7TX1XytdMxzzxWmbFtg8pv_h6y12Kg": "dancer, dance, girl, woman, person, human",
  "D42Jt6BOuvAt4M3ZOjPXOke6W0kpqeIOlhONzFD4eDA": "alien, ufo, space, extraterrestrial, ET",
  "2WNS97ktUfq73ynhvd0Ki2LW31Hf3nXDlmg4IUAWsyg": "old, man, bald, person, human",
  "_UKtd2UbD_fDcm0rfhTONOYKJCi2d0ynQIFXdUcOapE": "bottle, baby, milk, drink, food",
  "5oU51nt-ez3zNsoafwpXGyfEbi5ACpUawqTgreHXs40": "lollipop, lolly, candy, sweet, dessert, food",
  "069oQdxwF0Qy-hup6hTf9UIv1dHrbqPYQwkfkl-qfL4": "cherry, fruit, food",
  "lC6Zwrxdj2X9EkgIFixPbMDKJEaqgrG5wbVPapDco5E": "santa, christmas, hat, holiday",
  "5dKyTmgYOHxiQo-QBF8YbLIF_N6bg-GN_AdDH8xzTUo": "drum, music, instrument, band",
  "yqTdRWLEy0D1nF5qZEbGvv5ABY9Et09-u8m0HhAcFpM": "glasses, goggles",
  "gJNWjuvvJP91JLEumibxFoBaiqKEvcK8s49P7XllVrE": "pineapple, fruit, food",
  "xBO3RTpqh4GhGNgNM3BqgsjrflBHvlOP39meAVH5o3o": "strawberry, fruit, food",
  "ApYQW2H3iANEM7-OWqQ-UfsIFTsOEf2eHA_Tk4ZJ1v4": "watermelon, melon, fruit, food",
  "idzbpyi9ucjYfVWrfR637M6WkBKZsrP-34x7e5XFV4Y": "bell, holiday, christmas",
  "rJatTQ_Y6mlIATEti0EEDFxBws4uUpnDuiWo9rw03KY": "christmas, tree, holiday",
  "gvtdU72mV8ycj6XW0KxE3aCoTpdZoYDz_pgy4D5YFXA": "candle, christmas, holiday",
  "sYj2cUuQRQcpEPNZiGsOVPNvufYtyWUR4YrdBMBevkU": "ornament, christmas, holiday",
  "iylNTFWzISGseY7HLLveUbli051TyYuuNYHHei_aWp0": "snow, snowflake, winter, christmas, cold, holiday",
  "ann2QR90yjIKED6He-1otinKM1lOwT3z4LIXXb4Jtog": "santa, christmas, holiday, head, face",
  "HiFYwmS5MHJPIxGR7SdywamFatI7W6gFLcRgPZbJwE4": "present, gift, christmas, holiday",
  "4Dl4oQyxg0yUB7oEH12DPow_YMkHSFBsOLYDCcImtq0": "ornament, christmas, holiday",
  "oZKPw6Z6Cex9tBfhb7BWmiBPrsV2YicwXMo4unaCnpE": "snowman, winter, snow, holiday",
  "oT-XemJY3LNNhhJDIFv_z1TT6QpPU5cZ5Qnx_kQ5wG0": "candycane, cane, candy, christmas, holiday",
  "ZUiX7XXyhlO3mhRWsKLx_YgABg12jPjmZSssgZgJx4w": "ornament, christmas, holiday",
  "mmQkTUoEDBtnNVJNZy10GH3_c58aybuOeNoJv5pTo1Y": "radio, music, sound, listen",
  "1bB-31IMz24mz4XnEpCGU15q-Cu_gfUWUdH4ioZvjyI": "radio, music, sound, listen",
  "tal2wCH_bPOitYdPZQUvUSPGK5YobvV-rCXPH7sVGIg": "radio, music, sound, listen",
  "lVHrb3TZ1RZSPUNDhEWts1j1IrZYvsIb0J9BP_8ISLA": "radio, music, sound, listen",
  "auOIXmLNhMt0W4rv0SMeNTZtvZ91O5xIsGRSA5VlE2s": "radio, music, sound, listen",
  "nIGf1CHb9WEDO8uNV7uHdFK-Y2fLovO8EM-ULiBXT94": "radio, music, sound, listen",
  "ZuVmuvnoFiI4el6pBPvq0ofcgQ18HjrCmdPEE7GCnP8": "astronaut, space, helmet, explore, person, human",
  "EyirgG7VGK9riYxHLti4gxAokAw8_k3L6daUzskeDSs": "pluto, planet, space",
  "PJlVCnEJRm2GyDl5p5RVP4DibIFoajBHmiYuLrgaT84": "jupiter, planet, space",
  "9gM-X0G7eFbGizihNQhdII4zsFs1IfKAqsOCzLGHsKs": "uranus, neptune, planet, space",
  "kMBxjoisaL1DZ-7ak6zLFSImx3RRY4NHve7gCqZHP6s": "mars, planet, space",
  "W8WG8fceLh3-TdYFxObf20ntQbihqoF00rs1fTfMPgQ": "earth, planet, space, world, globe",
  "5xN4SsAp8xVajgeJqtCQ3lJQPKWkI-p4OMkAHfMJHo0": "moon, planet, space, night",
  "pw-OQ3-qGe1I3yowGRM6kh67fluY-vYw23xf5RTnHn0": "pelican, bird, animal",
  "QJ3tRMPbFwPPcCcF49VNzMwamCQbuQSsX1zUK571Hj8": "cheese, wedge, cheddar, swiss, food",
  "lVNXm2oALo8sflzv1MABAQOVvyqAZG-rj-uZz33klGo": "net, catch, fish",
  "-aKxWMVsXN7sT5Kax2DYVbBcTwThFGzlD92DgmJDIws": "elf, santa, hat, christmas, holiday",
  "PbV9JwD5FEcYPR-Vc3iQzhS6IzAqSuONNeBwJOLwKOM": "green, apple, face",
  "kolx6zUneBrQ6-FFY9u2ceXAFvYzb2Vzk5arWCeAfg0": "bee, bumblebee, insect, buzz, animal",
  "hCVuGiigHo78btqm8thB9vMe3f-R-TRU4hiQvuq1NbA": "bus, tour, city, trip, vehicle, travel, england, europe",
  "uU9JxPPYIO5sPbsPgkJLOBunfaWTtlJ4wBXKaF7uESk": "taxi, cab, city, vehicle, travel",
  "q8LiHS1E_Yo5RjxcLvHGEtDgt_-bppr8EusZvCyQ8uA": "cactus, plant, pot, happy, desert",
  "GMxPHdtKyzMnxWQ8YFiPScYYidtrdfYotZ9XIKt23Mc": "car, red, vehicle",
  "OSHdYme6_2_yeIOD0VeD-QxxqD6sjERGEZ664psy4uw": "cat, blue, animal",
  "EiEvE_d2TnHauFJtQj_jqA2NEWNqRalWuAyZ-wMd3Ag": "cloud, purple, weather, lightning, storm",
  "2eG_Ab_APhtSPqRrXWE_ghR3Z-q5URgJ9Os5l4JZrFw": "dinosaur, t-rex, animal",
  "3y8jL5QODbL5ncOSRwkOhnnVs5s_BbEjMKzZQHw17sk": "dog, cat, lizard, animal, green",
  "GeUl-JSjvAl5mL0yUHnoX7CaF4Pu0V2RgTrDb_sfdLI": "earth, planet, space, world, globe",
  "QutDsBONLGeLYlNsUxZnhNa2-MlNeXenAfDyPqOnbIo": "flower, pot, yellow, plant",
  "S-XNYlHoR712LU0EITXlSTe9MPrWPcaYpnEY7TiJF0w": "heart, happy, love, emotion",
  "UPO3MznTuhDo8ZXsu48VGdz9jZzg4E8IcJtTRINoKe4": "helicopter, fly, vehicle",
  "h3TRmB6y5O-VsbmFfxdJM4kYV6tA6oMY3yFrRZYSZXo": "holly, berry, plant, christmas, holiday",
  "oIpCHKtcAG61lI108pQgYkn6RNQKGltH_AP3XnPXIxo": "building, house, apartment, home",
  "OE9_2PiYStWYsHzegsiVlnS_TjPcXFChpDDUZqnPLC8": "ice cream, food, dessert, happy, sweet",
  "2OuSrMKBds9qJfHME97U1T84MQyPm86AaQ2eAHJ2p5E": "monster, cat, face, happy, smile, animal",
  "0-dLxdKueiy1RG6Z9xJ-01WNUpNMG3Jz42Nmw4jWjBs": "truck, moving, vehicle, travel",
  "NYpgt_KY71H05cTIg5_2-8YHHAHfIhIgDdrRPwAP8YY": "pencil, write, draw, school, study, learn",
  "IE1bMikmAR4lgc-H2-KvNRGWuclElV3MKSAIHkftAqU": "rainbow, color, sky, nature",
  "2MJEPyS641_rkck5u5igDnVzXTsm87IJmX91R2J4TtY": "reindeer, deer, animal, christmas, holiday",
  "nqMsoekPq1Fbeaj9wBDMPUlG6NwhKz0FTKRYyLwWOOY": "snowflake, snow, winter, cold, holiday",
  "_mEECIqaq-N6WDJ4QLI26VKjxUhcOtK5WZrStONeyns": "snowflake, snow, winter, cold, holiday",
  "Ve6QXI8r2w5lPm2WSZqZ0RIyGqrwedASCeEQojNEsJY": "snowman, winter, snow, holiday, cold",
  "W-2RUBud_e1PlHw03Mj73sqyLKibjZjNfyiQ1GWtvx4": "sun, sunshine, summer, hot, bright",
  "aNVbUvb4CzoaEMctPdvtaM2oivo6G5MP4DMuthHtbuo": "umbrella, rain, weather, storm",
  "FWmS0Thtp7x8X-ZNz5Cu-gP2XBW_UrYukbbwpl3hBqw": "bear, teddy, animal",
  "aDI5WNTa9D748Dc4YLLVPq4wbNaZFlIjwi7yzXDRB_k": "bunny, rabbit, animal, cute, sad",
  "RymX3i74KnjrAElPA4PMWKmsQIyUWOCtSPcu-aPPyxk": "donut, doughnut, dessert, food, sweet",
  "48wtgnn6Uc-ILAWu4UY-WsoYd_JQIIfaHTMT5PN30do": "elephant, big, animal",
  "Zq3_0iaZEIugWMZamAnGbnP0WhEcs77MWqJtq_XovNQ": "ghost, halloween, scary, spooky",
  "cBxjDY1KX_RvDrPlX_aR6Y3D1COro_SCmdlqXLiVql0": "mushroom, plant, food",
  "zSSkg9JHZwR7FyUnNBFieSk1zhybbzTPJAR3Am8RHVU": "robot, future, machine, science, smile",
  "3RbFa0wVPQ_dvdwvGcPjoP34tKXmgDvvVWH2UsDgY8s": "rubberduck, ducky, duck, bath, toy, animal",
  "eAK5aelIdDQJ6Fqbaqnj7LxYE6Bm63mA8ou9PYyaU7E": "unicorn, horse, animal, myth, legend",
  "EIsmrWovYkePtVSKOQN_TJzUpqKcET3nPksXe7r-840": "cassette, tape, music, sound, listen",
  "XMF38Zd4nnlBtaIpsb3FVVwF2KX5Rz_GDplF_TwR_IY": "cassette, tape, music, sound, listen",
  "PWfbnKhhFNg0GCBJX8g1XQccDrurFu6tpCrGmX6rJl0": "cassette, tape, music, sound, listen",
  "nRbyBmIGINUXKkDT11GsScp3prn5jXrFpxW0TAizcHw": "cassette, tape, music, sound, listen",
  "l7GAkHrUZY1KydakZUyOdoNM34WA5AEsm5v5vhiZOXY": "fire, flame, burn, hot, heat",
  "02qfqNBrky2vF65NYnQphJvzR8GkFrLqCqkYL_8Ejag": "goldfish, underwater, fish, animal",
  "ynMsNqGg8Hp7iyQGz7UkzvfCg8g9melNfCgbyILW2M0": "octopus, underwater, animal",
  "CuwrvIA6ML6XOGFlkGThnkPSnDq2Ld4Y90tzApsqk_g": "plant, pink, tulip, flower",
  "6OwRa9nWRdQ44ZIC16FQ2WIovScTAvuyL1xuhxJ8d0I": "snail, insect, bug, animal",
  "Dsd3p90qIgGz_wQtf92vKep1ZlDU-_t_9_ZzwYD0lkE": "dinosaur, dragon, t-rex, lizard, animal",
  "ADD-Xn117ooxO4rium_MvlrlngaQU-8YkbnM7E1dQnA": "watermelon, melon, person",
  "OkXiakvWyAR3JdGs7sfmACHjtCGb0_NJHm79Pxtg7Qo": "tulip, flower, plant",
  "G4XZ-p_LrXIEFWUpeCdxRHaiwkEF2jSJ2bu-olC2kZU": "kite, fly, wind, toy",
  "qvL_KcvxnCygIpVhzke3cEOX5HnoXWY1x16Zb1DmVd8": "tree, forest, plant, nature",
  "krQgB5XfOuhDpZfcVmoSEgfmg2k4F6oxdkXUoXgl_tA": "pancake, breakfast, food",
  "nq-iVMSTveCBH4aM5Me3b_SSJPgDeTo-ofoSfLIdjxo": "egg, bake, baking, cake, breakfast, food",
  "wV_r_zsZ2bTrlMbDkQT2lUZvNJ8KIr0c1u654SO-34g": "milk, baking, breakfast, drink, food",
  "wVSS_z56zB5VmRnDv2-Yi_d0IBv19pEe9Zh-RLpr-jM": "bowl, mix, baking",
  "1oE27Qo9to3jyJqBtZ3xRvqZytrD2wPA_cjMJop1lNw": "pan, cook, fry, food",
  "FmirAfBAbGhzWFgSsHLpkYO-a4FKEhOzxV9u2kk0agI": "spoon, eat, soup, food",
  "KKwU8WfVrUaz9d2KyIyu6qR82d9cR6GlfZ6TjmP0A30": "cookie, bake, baking, sweet, dessert, food",
  "KwwBi_4FiRPiiFzsf-HNfaOeo6cwDe49A2w_S9MKoZU": "hairdryer, hair, dry, blow",
  "BOZYt9mc28b-RFjkK276h3VuktiUKqE_67XiKqn4wow": "vaccum, clean, cleaner, suck",
  "jmpBDOfiG-5QDXND7NMAy9COAy1QJbM3AofqCy_BYX4": "sound, music, listen, color, rainbow",
  "aUm9i3ex3qqAMYBv-i-O-pYMKuMJGICtR3Vhf289u2Q": "plus, add, new, color",
  "6bh8gndQjTRgIEgAQvLW17e1ozrqEoLUq-QKkTIH75U": "cake, birthday, candles, party",
  "l_ssUJqrz9USWhmf21Vpr_rpI1ipo25xcyKHk6QbQ18": "bag, chips, snack, flour",
  "W9gf74I6zJr7RAKXl1KXIxsTVQiUrzxll1HQyF1q7tE": "butter, gold, brick, yellow",
  "F6PJXN2QJ2Wd5N50EmqJlYJd3P-6HP4-JBxpffEpQUc": "flour, sugar, rice,baking, bake, powder, white, bowl",
  "Cfi6UEaV8Uw1XEL22bbxkq55lj7SbujKKi42nZSIJ18": "flour, sugar, rice,baking, bake, powder, white, bowl",
  "AfILzmqn2W-XNfxyujLyHGsaM2o0RIJgYzsGcezmsiM": "spoon, measure, bake, baking",
  "gtOTgKRWViU1tMayXChzSe62P5Wty_KcMZInUuJFZnE": "5, five, number, earth, globe, planet, world",
  "LzHCIjs8D76Lkkx7rQFKKtq9dP4Jh0ETzAErU_HOT-I": "math, apple, bird, numbers, equal",
  "-I60h_nR-_En7ZdY9ISzi0W8cvZCKES1WB6R5NGRHvg": "cheese, chocolate, snack, dessert",
  "SqCzb61LEnSwRsVxHtD67BnPKaize76IA6We8-IPydg": "draw, color, pencil, art, car",
  "DbK3UJVyd32j-ecOsfr_aPAlzad6O7WBtwZ9SI5uegI": "laugh, haha, happy, smile",
  "39pgM_LI47SVTClvnh121gdx9G6ZnigNfBrz-lWniic": "car, animal, dog, fox, vehicle",
  "fqAuu4nSrOwNU-xbNVsGG-Om_PEe3S161UJ-nTXeBIQ": "question, mystery, ask",
  "4pstmgyYJHLmmRVOZ90nm5UsEZwUt7ifLaFT3e5CUPU": "detective, question, mystery, search, magnify, magnifying glass, zoom",
  "4UUM5uhVuXESKz3C4E3d7oP6fYJ7F8W3k0tB2LCZRIM": "calculator, machine, math, number, button",
  "InKMUu5w-OTU4K1LbvmZ533aSmldf-_Z-PjMXv24yUw": "1, one, number, math",
  "g2bCqc9B3ZGgd1aCCgSeUvpbLRHgU2UFeowtWLOHP0A": "2, two, number, math",
  "Lp0kH7FXAcL3RJ6d31oWfqO9rkAbOAqrrQlVir4bdt4": "3, three, number, math",
  "0H-Jh1ujRclugtZfXmTas84MTMfvkSYp7VeF8aEB1pw": "4, four, number, math",
  "rMTK7rXGlPH2XBSzAPdLB63uSJvcWEMaQnhT2CmYiP8": "5, five, number, math",
  "NEqSbTXGIEI8KwAOQuv1cn2xboLavOMjnpDaWV_d6Nw": "6, six, number, math",
  "oCHl1M8m7Exe9w_uKeuD5-6pgTYu3lzi3hlPqXUiY6E": "7, seven, number, math",
  "l_lgrtn81ChnLFHA0m5lYvqXKC-Jt4R0z4P0aiLKYUg": "8, eight, number, math",
  "zyiyRYt6dNMDaMYuXOkQQ8jN4C6_sE4oWzdCvc2_bE8": "9, nine, number, math",
  "AXu4LhB9lb7kPPtDfJb1Q7pBmwNqtGHX2eLhBosAKd4": "10, ten, number, math",
  "4PcvvM5CYc1nmeEHsWJcYcQW1jAbqePuQ97ccWGmPnA": "11, eleven, number, math",
  "CsIt18X9xr89kCL-Ul56ctslbxQT0-LrM2zzJgkpC5g": "12, twelve, number, math",
  "ZlfndSuvWt-3ww6cZ3q0DLA-rRZdKs8u1N0Ld2HIVDI": "13, thirteen, number, math",
  "JUz6hvPH5T6EigjWxC01EL5HLvm7RZq9XE_D5Tg_X-4": "14, fourteen, number, math",
  "c_H-W1ODpXZDoEfVHbpgGnqfsoxsn0airFm76QON0SQ": "15, fifteen, number, math",
  "Pj-UytMwmQ9TPnpV9Mlgkr8u4Dp0z1imr5qNErqbaTY": "16, sixteen, number, math",
  "3QWNlW4h2gTFeg70OWK2miSCHQ5l289RI7WuD8h49ho": "17, seventeen, number, math",
  "pgsljINMdVOsLpqQgkWWRIfhROeu948l05FL1Ib6vYw": "18, eighteen, number, math",
  "2Usm3Dsh7Y86Qr_81c4PKwhTXIjIJiQQ7f_HQ06BGHg": "19, nineteen, number, math",
  "LqIRe47aDoLozLO8dGq-JOSQbiQYa1UjTHuKA7HhwnI": "20, twenty, number, math",
  "QMBnIEfJfklqsPD46osBnrCc_5xvrs9_w-zM_4kB8Tc": "21, twenty-one, number, math",
  "fNopSe_PsqnSzVbH2abysJAWgLgIwtMlD-aij4RMFuU": "22, twenty-two, number, math",
  "nPdAreUXVMhEoLlUNk8tC78ZbPds2F6hVtYVFnukEu0": "23, twenty-three, number, math",
  "5WxPsNpiueObJMYngnWvveoBl2YHFWqutJ_fn6Ty26o": "24, twenty-four, number, math",
  "5ndmduxNXvQlUq4ToPr8-VcHit_QWbFeqWQlg1PqweI": "25, twenty-five, number, math",
  "6rRWGLFT9DqA3uc4a3vRkuWcddKpgk-ZpEipeB-4qYg": "26, twenty-six, number, math",
  "Xupe_ZGYuZZ2I617gp3sYcgLG32-T5-107PdD1SdKAM": "27, twenty-seven, number, math",
  "C3HF_APFyYVfTqsHijZ7Crus7H3GOqRdz2wIgoPhwNI": "28, twenty-eight, number, math",
  "XJiJiGBImKJ6tuubNu_jB6U1vGwIWL2q3VttEAFOKFY": "29, twenty-nine, number, math",
  "nQ8uyd1lYELI554L1HFRx3Jhl5Br5HdLWwPELKAUKK4": "30, thirty, number, math",
  "oCMXp05T6goR11wDmp2jr4KCEi8_i1KBfISZgKWyU48": "book, blue, read, study, learn",
  "KmFxrz9rpfTJgz_JdVcvSsmOmt1beZZANTXoxhX0r4k": "tulip, blue, flower, plant",
  "CzHPDrAenjxNZ6LiDTk5bd_TOqFaINZFKGbP7Xq487c": "frog, king, crown, animal",
  "ByDf_m-0HtI6EogcFHoIGGqigQC2OT-4WsHjL4B53C0": "book, green, read, study, learn",
  "UdUW2IJDNhoT6yE8233iHAY_lIIHRlYz40OPcBvtRP8": "diamond, crystal, gem, jewel, treasure",
  "XJSGk9bwZRtZ5bD9jEm-bUsA3kgJN0G5a9vMvudFDz0": "cupcake, icing, dessert, food, sweet",
  "IyBdMUNh5zfc0t5poUq_fFJYdibk0Yu1QZb75rfuCks": "monkey, face, animal, happy",
  "ej6B6bOJo-lKtlmoKP3zCnzmd89B1R6WgQGti5xVvoY": "panda, face, animal",
  "iZoAZGVVtrcfEPfnXftcag0itN17SjSnxSV9pD4aXHA": "book, pink, read, study, learn",
  "99i8i93d17yfLxD9cDjXfgSL6B9A0XfIkJo513VYJ0U": "book, red, read, study, learn",
  "vGX-_OnsJfn1n1rHEr-qvS-GU3l0W4Fchs2l3pcKVoY": "tulip, flower, red, plant",
  "6FiO3cLOQejRCKBsVQHRU_YcwxWr_JdHRkFex_SjRYU": "strawberry, fruit, food",
  "kmmtUHk9_SEN1dTOSXJyeCjEVkxXmHwWDs36SMVqtYQ": "book, yellow, read, study, learn",
  "rRWhWIn2E4ujV8k67ZKR5xg3gK79TYB2xRn1sZ0gdJY": "sibling, friend, boy, girl, brother, sister, happy, group, family",
  "0Iqxsda8bJiWuN4SaGiQiOPuAfZWS1Rbzae3d7P53RU": "clock, time, hour, minute",
  "03wHp3-hbFnLZZ2GEwjLhxaTZPVYQcnEfOZaWzcaiIY": "pail, bucket, shovel, sand, toy, beach",
  "rqtgnTScveVE-cRFQmt2sWlHcfsy2wv4LQs5IkgDRG0": "scarecrow, field, farm, halloween, autumn, fall",
  "bOEw9RBCHNv1ZRssedCImm4dG0ZwU2vHZhZSqPDp8DI": "pumpkin, halloween, jackolantern, scary, spooky",
  "jmttFm0WauzZ86LaP5158jjkfIKWY3dmTL9HvsYMrps": "volcano, erupt, lava, mountain, explosion, dinosaur",
  "8AFUk8VapNpJIukkfVEgYOURDAbf6hn1M0QRnxqNJ1g": "apple, red, 3, three, fruit, food",
  "75CyQHuG2h-4-wN72mSKWFpZ7Q4dRlT9s1E-TxEPDaM": "snowflake, snow, winter, cold, holiday",
  "WIXDcqRSfYLkOeHXS2LYOk4OXc4qXNVD0l4GbgYReVQ": "night, bed, moon, sleep, tired, star, bedtime",
  "xeJEqhQBmCj3J5Bqzpis8mKxO_pVJfezce2P9Euc57c": "earth, planet, space, world, globe, smile",
  "zCT_Hk1xPCXjNoDH1DOExIotagnXHZsNKVuRD-Khkpk": "crown, royal, king, queen, prince, princess",
  "t432FuacEH9YAPsUI6D2veHX07rKXphRTTZiX4rD2hY": "pumpkin, halloween, jackolantern, scary, spooky",
  "hvMVSxIBQCuXtiduoF_ibk0UfQYq-HqQfMK7jIo1pYo": "pig, piglet, animal, farm",
  "8nusBXA2NSqRULkZFNZPdj3JXj0ZsfK9Q8891STOLWA": "doctor, nurse, hospital, health, medical, ambulance, bag",
  "1OZdaIQcOVRqiQA6E98DXpnN1s3qQxhSeqtJ_bO_RIw": "planet, moon, mars, mercury, venus, space",
  "Cmkw9Z0Lc9QxR5bGRF7LcsaII_K2VBedcDSaxFnXam8": "uranus, neptune, planet, space",
  "n2PUPP6Vun_0l-neSsUIAupzgiM3it5nbiP2LmBfQzg": "space, ship, spaceship, rocket, launch, fly",
  "dbdrlOu93S2fLJJWbfvjBn-GFMXizMWHeRfpc5_zJEo": "space, star, galaxy, universe, night, sky",
  "QJJmCchxZMCH5GUYYzM_MdHL-BjCmnRQG86CbNxPIIA": "noodle, food, bowl, dinner, lunch",
  "uPYui4NoRIY1brSeH_A0tJBoN8vYRb-EKcjenadtMl4": "saturn, planet, space",
  "QMV_27ZcXDHQA82HVE9-3DWyiDePvO5sHqq-K3XKo8U": "turtle, underwater, animal, slow, reptile",
  "9ClUfcbNwIhiqfsLroIeIZImMLVb06PsNEvXTeEmPm0": "seahorse, underwater, fish, animal",
  "VRI-H6K3plgtddU7niOcrQWoFLnRzMnNcBUlXJ1Tn4k": "trophy, award, win, prize, contest",
  "0uoUGOzzx8vs7LN12aPK0GG5bYP_XFHMD6Fx3l4-phA": "sibling, friend, boy, girl, brother, sister, happy, group, family",
  "VNuEqYkwEmNf9CT2ni4yYvM6jFQD_2ldq8dNYzxc6-M": "lightning, bolt, storm, thunder, weather",
  "g19hi-1oiNldAcU1nI-atvOm6RxLTfNDRTSdcIA57XE": "dice, chance, luck, lucky, game, roll",
  "ivZzvBjDfbIrQTvksx-sDGPTGHJZtKysD0aobSQqUFw": "guitar, instrument, music, play, sound",
  "LWScTB2_5vBGOdWqyxE4Ijt21fWG11Ag-9XFK2eJdqA": "heart, broken, sad, love, emotion",
  "n42PXAoEQEdA5tQNqJ5UnuX2FlC4nm8RyzK34QnsBnw": "mummy, costume, halloween, scary, spooky",
  "I1qmyTd1p6jDMw1u3XtuIrAGv7G0vOaQxYCCzUFeSkk": "toothbrush, brush, teeth, dentist, clean",
  "p_yLNC3TPtuo8MNv5WSG0q5aqTPD-WRRRWYkPB0cbjA": "bear, teddy, animal, plush, stuffed",
  "jCX3fTsUUd5lUNe0CZpPXF0AiSnsDABcqOAP2MoTDLU": "guitar, violin, string, cello, music, play, sound, instrument",
  "V0APu-QUyc7AHuad6vusSV4gwtgffkyYqRshCx7VyrA": "night, moon, mountain, sky, star, cloud",
  "Z6BNQqPkzivwesZayq1W3OQXBUh2Lrqf8KS6xYfseME": "spider, insect, bug, animal, halloween, scary, spooky",
  "lDuLv_FG3T-OFT0yOZAzZ0WQNwhP_a-kTF_V7TzcrGM": "flower, blue, daisy, plant",
  "Kedwx3AqrRLdx8Nf1x9nXDwVkCHDwE4uWKz-ezhKLZc": "chest, treasure, box, pirate, gold",
  "7x6t5HmTYYM2ue1U4XmmgMCwq2UF8NKlqbaM02uwjFI": "window, house, home, building",
  "0p_wRaMVVcc7coPviQhifIOlJNuVwugmA5GlPdoC5LQ": "3, three, bear, animal",
  "NqPcvCvLIlcSTuqnNmWZkHnYm2PEkhgpLXWqUxfHaxM": "3, three, fish, underwater, swimming, animal, swim",
  "8lzu3BO-dap2zgl_YfUGXfM1HrkMWuRKsRo-autqwqM": "alien, ufo, space, martian, extraterrestrial, ET",
  "eY7QSnw2Nbv5fSiXuo2zATtdJCdKjaSJG3mVhEV0ZSQ": "bee, bumblebee, insect, bug, animal, buzz",
  "bb4ZjpbUMRVNaNPthJPKj4Yphg9gU-uhz6K5zJsP6NE": "bird, animal, fly, wings",
  "lqbDQVltvARrPEuEZHqzX_HyHwp6zwgn6kI9HJ-6JW0": "butterfly, insect, bug, animal, wings, fly",
  "ku1_FZxgT0yxAKZIAB2qAsBMPgffMbms8RBe212Kq6E": "camel, animal, desert",
  "PNxMfq3eGG0v6cQU8_GToLgeyBKT0tSLPFYIeF3A-fk": "cat, animal, pet, meow, kitten",
  "WEc-l35N7Jo5WAJhHvb1E0kSNAD2Vvz5FvvZAnuURFo": "cat, animal, pet, meow, kitten",
  "i4L0i7kgHx2cEZD-6x86MQvKknUMR1Fvfi9TbVvWNp8": "cat, animal, black, pet, meow, kitten",
  "YMIUBFbvjGRuGSOl-pK0dYYvWPc2nbHCrNc_hCyNCKs": "cat, animal, black, pet, meow, kitten",
  "071ImHozOaim55FR1DFOFal7Vk23VubwRF1QSWAwx20": "caterpillar, insect, bug, animal",
  "mrVNFnlSqUG53HNkEE9gGtUokhBNsj03dCvXIS43kD4": "chick, chicken, egg, crack, bird, animal",
  "rxnpT_sjyovtCyolD3aP1-YUTYJy389WF4v9OTG3yoY": "chicken, hen, bird, farm, animal",
  "OyaInKgKUn4cDLOk01Ik27aHGnXO8cZmfY7YPVWDigg": "chicken, hen, bird, farm, animal",
  "5cu_PFrz-N2ZZSgedcuG9pZJJtZ8Psc4uLiPQG9mmkk": "cow, animal, farm, milk",
  "Msf0MVzvvBR5kZ-fKllfwYqyYRJmmZImhSVyi-PvW2Y": "cow, animal, farm, milk",
  "ehpudtb93aBiOCu9JAsMNFesc-WYyePiHqimBk9SEGg": "crab, underwater, animal",
  "-Ho_h8pZ9fHWe58u47lU7a1wGYhW6uv2tU833DOc1DE": "cat, person, animal, bear, dog",
  "RSsi4eQvVffIDMHbq3cuKn0ebSg0X-3Y-ZxrAorxycY": "crow, raven, bird, black",
  "ga7epHZpDxtu1NM9JTK2P1tF4i74t4PTFzC17xiH7J4": "iguana, lizard, animal, reptile, dinosaur, triceratops",
  "oA0uDzECScQNI3coXSC4zAzTlm5wo79souCDCMTWTcU": "dinosaur, dragon, t-rex, lizard, animal",
  "GI3M1UrMEgOIAWOYcrX-oxy-4kTVLJa3hX2FawE_AXg": "pterosaur, dinosaur, flying, animal",
  "qtKW_vMOP1EI4uGRHh_lbkm8L6fRFnbu5Y3FVg_aZCo": "dinosaur, lizard, animal",
  "1JTvH98kWsr58yfYoHDMih05d2P-IcXs4jXg9tlpC2M": "dinosaur, lizard, animal",
  "GxWJ2QK535MrMBCDwMr7H-HsJBchvOSlZWucaXtCAtw": "dinosaur, lizard, animal",
  "0MruEsckVrn6rmE06QOKipQwo9Dshj3R4vcOtgL3fkI": "dinosaur, dragon, t-rex, lizard, animal",
  "NU3U1n5x9luSXqMPhzqFT-BbPfW5OTqpIaWwgu5KvLw": "dinosaur, lizard, animal",
  "2wJjCdQzoIoyoEP2lgTqk5tXchWJMEWy9lzOv8dvF_c": "dog, dalmation, spot, animal, pet",
  "kLHPhB4j5VlntCArCrbQc-Ldz8GwOYoi9fkIuDqIdP4": "dog, fox, wolf, animal, pet",
  "z4Ym6A5k39rayNhLw_ACbTjdMUOnYk3_k-i8zc33BM0": "dog, wolf, husky, pet",
  "ofY8wO3KyMxEZ_7d0WVkqFQb6gWFmaiZ8oPwnTUHHS4": "dog, animal, pet",
  "Ym9hfMXXZppz64QXKOOVDLWHMe7hfW9HN88zSNviAK8": "dolphin, underwater, animal",
  "lNJXbVsI0SgCiE245mJRR_2-7j33GBcLtZP3IGG0QEM": "dragon, puff, fly, animal",
  "2lZnNoi3tl7Ny6UrpGi7veD7_fsYZpnavjLil_UaAoY": "duck, bird, animal",
  "RkKyAsLouBHi8c2wXoHgkKY4moLuqPLEzS2kJcAezdE": "elephant, big, animal, trunk, zoo",
  "OCEW2w2SYQoguSjusoLeyuLbGCGQmpi25CqnapwrwKo": "elephant, big, animal, trunk, zoo",
  "tcosG5RiKiPWIVN4uvuIcwLvVaqd2czX2LNPJ7vJCJI": "frog, animal, green, pond",
  "DefQNc5sLuo6uYsi8pnJwfeNqm2CpQfX2-1XchvCpfE": "cloud, weather, rain, storm, thunder",
  "S_0FEUZMt-RQDQv9VaVI_JSNhNvKtW3eEUoc8ezLI6o": "giraffe, animal, tall, zoo",
  "8hrAh4k9x_xqJgppsoIMYm3mNGwqPop7l7wCO5IXF5s": "mouse, animal, pet, cheese, small",
  "XrJzTakzh3TnCyTHxdzwe57iNjQNjpNKmjQXoVShTYQ": "frog, music, headphones, listen, sound",
  "aCsotezkLPo0JbwPIlyOdrAZIphnXkoS9j0ig8RuvSM": "horse, farm, animal",
  "KqKyM4ABicNZYzh3jUAQJvf1bX-yGyHoq6MFhn-wixk": "horse, farm, animal",
  "AbXHxbSG7cl9Ga1x84K5oLDQWrl8hL35DXzsJ_j6D74": "horse, farm, animal",
  "nsxv6nPTvEoC0OQel8uz3NA_2fKN_72rwWjqU1SJ0II": "ladybug, bug, insect, animal",
  "fzwDNKwmuiTItf7r4YzYyIiiZq970ALmI9h8KdX5ihs": "leopard, tiger, spot, zoo, animal",
  "bCPBiwHWCbzCDObzAZO_mDVGDROHTKIK__Lkb3mDFS4": "lion, tiger, zoo, animal",
  "z0nbNb2t5CL0WmA6EGkGP996tERb0r4unFWJ6a4CZAM": "lion, tiger, zoo, animal",
  "AWzbSaxm-wFt8PCF8vjDRQ9nh3IjLbDBMprD_pwG6G0": "elephant, mammoth, big, animal, trunk, zoo",
  "oFzgis8-gvJZMUC0TvhWD6zxP1nnU6xEaS2CUK7ssP8": "mermaid, merhorse, seahorse, underwater, fish, animal",
  "hS_zMzLq4_M4kz_JieVPaUCHH6cD_k3SxO6GGoY9Mdk": "monkey, animal, zoo",
  "1uv7nVxil6eEbD9iUlTLQIPiRnH_MUC9hRGkCOKs0eY": "curious, monkey, face, zoo, animal, happy",
  "6n585_H2EwO4xZOxNGqjASB6yFxaEyQGbDWvTd5n1ZM": "owl, wise, bird, animal",
  "WRc1s9BL0uJL3H9q4U-JTdaLdUf7sIXBMHKu6If5ktQ": "panda, smile, face, animal, zoo",
  "BmMQ1qLpJK8L3rJwgqjBldJmM8hY8uTZfI_O8tJvKpA": "parrot, bird, zoo, animal",
  "S8su8IPwot9gyXdQFLXntYShFqWF3a_Qkpq40IodRhw": "unicorn, pegasus, horse, horn, animal, fly, wing",
  "E38qf7roid_gsP3kxwfr801x6IyLS8c_M71WvMEtlzU": "penguin, zoo, bird, cold, ice, animal",
  "ULZ8IJbGYBXs3riG1yZqmdO2qElrvCCGQWCmjs5Qb-M": "pig, animal, farm",
  "4VTBoF4lOMtKKOfnZUkul3vVnnWzblcXg4-8X-6lQuo": "bear, polar, polarbear, ice, cold, animal, zoo",
  "pY9H8pKr0qZ3k1BhUCkdv1KplQsiUV1F1-53MpKWNT4": "bunny, rabbit, animal, pet, cute",
  "8zom71_cB1typ2d7vPeQ3TU1Q8F8Oh0lOyU-rRmcktY": "rhino, rhinocerous, animal, zoo",
  "pcGl9aZOfMwiNUm8Rfu4wRYPkBuDiEB5nwwy76aVtCM": "bird, brown, animal",
  "OzXpk-yzeC_UgjBk8gN-IgkGG1Vq4GCLA0831DvB2fY": "robot, machine, future, science",
  "P2IBUatvrHeHYqSJCjMMwLb5Ag83ok65MIlhEcc3-ME": "rubberduck, duck, ducky, bath, toy, animal",
  "_f_YgSSRKXTHBtHCQ8dtM4qT3ZWtmYmfSkyAd6zwvXs": "reindeer, deer, animal, christmas, holiday",
  "PpGfXb9VfCWkWWsieBfMSgDJiJW7xg_HWmsiAV5QqS0": "shark, underwater, fish, animal",
  "uQJ6upobDngGQFqUHpbBIm9Ensi2BsS_KALp0yaFA4o": "sheep, lamb, animal, farm",
  "v5WHX-GMWL9PjxAyO4UxHVUwHQZkT2LOkAW2bj__RlM": "skeleton, skull, bones, halloween, scary, spooky",
  "rfY0tNN4iGrW7oC4-KhnbcvMHyUuRZQ7S5LO2S_eyUU": "snail, slow, bug, insect, animal",
  "S1yUSKQjD5lsSWRetdOD_GBruT6eAoQ8yA_78kArfCM": "spider, tick, insect, bug, animal, halloween, scary, spooky",
  "guMcOCUsn3kj7qROsooN2NuP5HM6kVe-2hIuupWEM2o": "spider, web, spiderweb, insect, bug, animal, halloween, scary, spooky",
  "-PIOD2SyL27xE04V_ljMDwqi6lbbsgy11WzUpT_1A0Q": "star, starfish, seastar, underwater, ocean, animal",
  "yEXasdXNlLxznl0Nla2LiyYJZQQsxDWvqjdYi3bwP74": "tiger, lion, stripe, zoo, animal",
  "7EbO5pwdEg1JBH3Ehbf0uLGLOw0uVQ-jd7mSr1-GFr4": "unicorn, pegasus, horse, horn, animal",
  "ok-tpFuP297-0suDhA_KVllY6mB0RKY311luAR40ADY": "walrus, tusk, animal, zoo, underwater, ocean",
  "CjYXCd2kKP39U52AdQGLf7TBfKaZBJKfI1k0SSuvEhw": "mouse, white, animal, pet, cheese, small",
  "3cb-9QDl3x7KPeW37JNIypjpNFa_2wWcgGinQxd3BLA": "bunny, sad, rabbit, animal, pet, cute",
  "P8fbnIu57nIqMs4gXgSFWKI2fnbw_TJmT8sF0ad0rBM": "worm, snake, hose, pipe, tube, insect, bug",
  "cq4dD-cG71rRZdOGyRHmrHJ9t4zKq8X6apD-QT5N5fs": "zebra, animal, zoo, stripe",
  "ycql295408KdkyV-8iVPtZXAVdTpzVZ0v0nSgSMQZEA": "apartment, hotel, travel, beach, holiday, vacation, relax, palm, tropical",
  "wDOz0jwui08YMgZ0s28VqsxiNlFiEb3i31IvxndZd0Y": "tent, camp, outdoor, adventure, travel, vacation, nature",
  "BqUWAfKjymu3yzksZkUki8jo4D7Nz-kb37pyDxh1Sh8": "castle, king, queen, prince, princess, kingdom, medieval, royal, travel, vacation, europe",
  "VoRqxglc-LS1d6m_GAEQIKcQIiFkjsBRvr_UCSit3qQ": "church, castle, religion, medieval, travel, vacation, europe",
  "1mcC03dQGFBPgYas9ANNAyxJajRGvMQOyPotJZuTcGE": "tent, circus, carnival, fair, festival, party, event, travel, vacation, bigtop",
  "wAiHNmdHEjT0KesjKpaAO-4JZxTE6lXRxYcjXPrGaDQ": "factory, building, industry, pollution, smoke, chimney",
  "gfMn7DCujGzPPsUOp2gndpQESkmh3mo8Tb0hdGUIotc": "building, apartment, office, city, house",
  "OYXTfWhhSv8NJXox2gzBxSEqDrBs__Eh-BAMxpT31zQ": "building, apartment, office, city, house",
  "uTrEg5trCFQqPtDQZ45rINOUPQcJRHVSMUI5DhiZ_1A": "hospital, building, apartment, office, doctor, nurse, health, medical",
  "4EKDrmrU0mOCi4Mgtha6BiEOIDTup3OMKx_5_yF0Dwc": "building, apartment, office, city, house",
  "knC6bDRhVurC4kHD7o_gr7M2kg5a-dheJcF-kw3MOGk": "building, apartment, house",
  "pl2_OZ8AuXA8ALRYWvT5bky0KLWlBP40EFgXlCS2Aoo": "building, apartment, house",
  "wcdeZ9rKzIL2I_gnERP3QSsjqNL5ogwrQcJ1I-c4PaE": "building, apartment, house",
  "kuGdDcQB7eTGbJt6lQT7XrFd-DX3898ctaobmyAcHTU": "building, apartment, office, city, house, clock, tower, england, europe, travel, vacation",
  "AxvEu_FAkbJcokLFAVgpIegJYvHPYWiMz1Ypb9Iq_FA": "church, mosque, building, city, travel, vacation,",
  "o58KWvO9GSCnBqZeVaRCjj4qnbkl8JNpHGfXBN8jCBs": "building, apartment, office, city, house",
  "tfcKCwB0w5wyGyheKPub6vrQ8RyehnpKQftW4xZb5FI": "building, apartment, office, city, house",
  "uLiWiZwTz-IOiNZoONPcxOBRx-iC_rrXXFELMeGQuao": "building, apartment, office, city, house",
  "m42HvInZl_7FAQp-S_cUk2IH6GdUaU_jTTfkD2pQOOc": "building, apartment, office, city, house",
  "drIc5dqzY1AGdUfDB1Kdo-w8Y33E8m1oajFC4oAZcJ0": "building, apartment, office, city, house",
  "iuDSEhhr_NX0SWVv30Tf39mZc2_Mw761Fn_QaGEsrus": "building, apartment, office, city, house",
  "9bVieTgJKZuigv7eaFHPbmvKZIGVq_PAlXGsW-c5ebg": "building, apartment, office, city, house, whitehouse, president, washington, government",
  "10CAuPLelIVFksfJ5-dFRliHsNzEMBHb1DuD43vaO7Y": "building, apartment, office, city, house",
  "h3n5ohzovNLU_-BUCD-yW3D4jP7O74hKk19paZZCOgs": "building, apartment, office, city, house",
  "XPr0F6yDowK5h5Y_zUZSL6GPaVNfY9SGuPl5OxD6oPQ": "building, apartment, house, snow, winter",
  "4dTXXAex0ID5x0PhCZpyKBndFgMjqeOZDnAL-qmTIqk": "building, apartment, house, snow, winter",
  "GwrgbVn6toPDEhNjvpkhh2xTtzWyC49CkJs6dlkQ8-s": "building, apartment, office, city, house, church",
  "6l-zk6XYlrNxIB27DnNwzoflj47KWA9crRVZdlSj6nw": "beach, palm, vacation, relax, tropical, island, ocean, travel, holiday",
  "LuVvxhZfaCOx1yjyALt_8xm806jEea5Hlct8p79kDMc": "train, trailer, travel, vacation, transport, railway, railroad",
  "j_Sz4XBT1XpH76y23A1n3QWbCuMG5zLDIl7ECp1gmlE": "ambulance, hospital, health, emergency, doctor, nurse, medical",
  "N0SgdI6KuAorlw91MTanUFfBXvLhNiO2WXGiU7HouNg": "firetruck, fireengine, fire, emergency, 911, rescue",
  "cPAO-bMWYaQ4h09ZJfMD7WnhUNK3JXOdRed4dVzI5ic": "car, taxi, vehicle",
  "Fdm0qExhoZXJdw7Wt3lrhB0C3i3iT6O2cRTSX7fD25o": "police, policeman, car, vehicle, patrol",
  "wtLvkMhrp467xeCHt-qEaVn8Cl0c_jE1mUIKS5xJTc4": "alien, ufo, space, martian, extraterrestrial, ET",
  "lCrBvfXuqgMWLLSUw_9Z8i_LdOnT9d57rdl3KkjTZbI": "helicopter, chopper, fly, vehicle",
  "p9mbtq-oorPMaAgS8D-lKKDzv31AdjAfrBbfkM37tB4": "helicopter, chopper, fly, vehicle",
  "UrFx-26vO0Y3nOe7OlYVeUd97ikpQ8WC3MgjO3ynqo4": "balloon, hotair, fly, vehicle",
  "sOnvwB-0HkhblZEVSZp5bEULhy1mF-gCyRXfnJECYSQ": "airplane, plane, fly, vehicle, airport, travel, vacation",
  "1sUKL0o9of5QQMavxwOBdPYD4eon4IOXCQNLab5E17U": "airplane, plane, fly, vehicle, airport, travel, army, fighter, jet",
  "VSFiaGVBUIVKt7qhfO9OVgqraRmcN9i23J4QE3ojOzA": "airplane, plane, fly, vehicle, airport, travel, army, fighter, jet",
  "_txyVO7efmOQw-mMbWuO0IQnKnLZV_XN7OS1s_4MdC4": "rocket, space, fly, vehicle, launch, ship",
  "efDHQxHgoAeOCP7ajC6-fvBoWohOJGfT27XefCx9EZQ": "bike, bicycle, cycle, blue",
  "FjV3m42wYtF1MpeE2-5Ee_RnKT7cVq1yjhA8AacOAO4": "bike, bicycle, cycle, red",
  "JXn8wMue3dosSqog6Sstl18WnZSNX7guaaG9eDHeH0w": "car, red, vehicle",
  "gVkQHRCsNFhknB6KTqk5r-qK5yWGmb3tH3rPWYwnsE0": "car, green, vehicle",
  "fv3Up2LFWf3PGJkGdD7Buv6UKtaA8a58gHMPiz69-mo": "car, yellow, vehicle",
  "8q2J_Fw90eI4pDB7ba6fuZIMH744DiscoZo8A4vfqc8": "car, blue, vehicle",
  "fm6UxOjks4mgIORIiEfjQSZnGCeXRwVYnRo-fPrHliI": "gas, station, fuel, pump, car, vehicle",
  "z5y5EfVe2SFe07qFzTISnm44dWreGzKGrbmspdxfaY4": "icecream, ice, cream, dessert, summer, sweet, cold, truck, foodtruck, food",
  "wZd0DZXsSMiOi1XLIHdSGLmxP4NiRP_bQr-JRPaKv3E": "tractor, farm, vehicle",
  "5ycXAT_ZybBan7bsDusL_64iIhWBOHT2R8YbG2DIAcM": "tractor, farm, vehicle",
  "BtZqzzZZR5t-LpupjNivcMa3ARvmpvS4VP7uS7X_T3E": "traffic, light, signal, red, green, yellow, stop, go, wait",
  "z9MF-c0NLCFNV1vSqBrOiVCjUlVDyHAAICghqQgqbsE": "truck, moving, vehicle",
  "9FJXzjocF8249-Se_rLHkatx9AAyj_S9b9169Srx6k0": "truck, moving, vehicle",
  "1WCvBzd3kF5ggxJEo5w1gEfEQTUgNfOVblR6uJ7hj6c": "truck, moving, vehicle",
  "y2fz7DAVeJ_wgoelqyjjXZFpSnVRT2GsnDmFvisJk9w": "truck, moving, vehicle",
  "AVSvfVJTmw3noBZiqUGxgeku174eEzacTvLIXbkA0t0": "boat, ship, sail, sea, ocean, vacation",
  "8tUxB2j_HtGiBqKTjZ--V2SHL84eNLxySr4ioYuG4RY": "boat, ship, sail, sea, ocean, vacation",
  "xOCFaCT_4JXzARNyo2APT7oncFZMFOy1wi41ztdrVk0": "boat, row, paddle, water, lake, river, vacation",
  "gxr8HxFEK0bvpI15oV_ySCyv8TvUJRDnDQVPIf5Qojc": "pirate, boat, sail, ship, sea, ocean",
  "b6RjCz8gkiBPFOTlEtp_BUfWZOhyhDnPYKCfeslUxg8": "cruise, boat, ocean, sea, vacation, travel",
  "joTFUt2vjymayfs56gAjaYEGCrvk508pAnK0GlZzuP4": "tourbus, tour, bus, travel, vacation, england, europe",
  "V75bsVYBu_yX4IJHZwb_gA9QNXflwmaTl3E0fUkQnj8": "school, schoolbus, bus, vehicle, learn",
  "l2wirXkGvqgZkn4_138VAkgXuquAhWvnBZ-SHHNT7as": "car, taxi, vehicle",
  "IKInb8XC6sQoD8UcmWGWIuK-e4rXi3hLfEiFgacc2Jo": "car, taxi, vehicle",
  "97XI9ISlxROKnPtE21khTHl1YrXY4x5hqDCQ34F81Vo": "train, subway, travel, engine, locomotive",
  "qF5oRCPSPQ4U4w2RzVTnbdTT13exX4qCt73eKyVlQd8": "pirate, soldier, sword, war",
  "QSDIptWfmbg470A3WXqXrVJkJPSqG2PxVEkiaTn2jJg": "map, pirate, treasure, island",
  "MYHS38F4VQ-2TcUe4gL43A1ElG1d2S9trFuY69Z14NY": "anchor, boat, ship, sea, ocean, pirate",
  "NWX59hqZIOl3ER_EiHUgvo1mdz4sRXBKYCMVDZGqHoc": "pirate, sword, fight, weapon, rapier",
  "X8MK5IpypHxOoq8FvN3iM5teILcTsXeHYW4ZLnd59pc": "bear, hibernate, winter, cold, snow",
  "imtAZeTBsULh8B-l566RCZSaHNhg6KiarpLPGxx25eE": "nature, tree, path, road, forest, park, walk",
  "XxZWHfpi04pa0d7Qkul3BN50D_vN-fTjN5ThEx1cqIQ": "candle, flame, fire, light",
  "_-pXFH3N4h7BaqH-qEEUvKts6aNsY81ik3HSApisct8": "snake, serpent, reptile, animal",
  "Pd5le4qFBL23s_pn7J15jlrpmVdkjqaIbNT2uLygiWY": "sloth, hang, slow, animal",
  "7JN_S7lQCXpuCyJnXmLuwFBOvz6MpjRg--coltsS0mU": "dog, animal, pet",
  "Thtokj6diJTKKpvwBcOjlGK4WbspWut4R-QII8h9q74": "piano, instrument, music, play",
  "EA_HJfvRiFQuHYPGByUt-8rwwOqIGX0ohoMupmrfNu4": "bag, briefcase, work, office, job",
  "89_fZIqCib8SOTqfmNYrh4kb8tyEctpVs_n4IP3PWdI": "heart, love, like, valentine, emotion",
  "llZXxWg1tvgvmhT5RdfKjKAq8crbsj6fOVOiKzBo_tA": "beach, ball, beachball, summer, vacation, ocean, sea",
  "sWDl_zKcgC6eIsgSkRc1Dun-LPDYlPr3XEqh6SRG0EU": "star, moon, night, sky, space",
  "dHPdJdEkCawdCBKCk3pgVE0cCyK5QFCK2CXo72YTcJ4": "knight, armor, sword, weapon, medieval, armour",
  "UhaJfp8XSavqQ0K5noL-G9VOw5jEwBOBRpJz7Cj9lcM": "bone, skeleton, skull, halloween, scary, spooky",
  "Cf4cHK7SbsprRYaTTz-6-67XkKFhpIg3ihgkGPjpoVM": "fork, knife, spoon, cutlery, eat, food",
  "qpo_jljtGCqyxy_0OnE79iFUuJGAKEv-4kPuf6a2uGY": "trumpet, music, instrument, jazz, play",
  "eIobCEsF0sCcjhN6a1TIAMzvbScLallxBIuyyMPhp4c": "coral, underwater, ocean, sea, reef",
  "_JBN_5xIJjlE_GBuwLRYWNJ0Y43zliw3UcqKGOZeTUY": "fox, animal, forest, nature",
  "NdIUBXsvy9w0Hpe0zgye2BMqU4EjocqTENaNSYLjUA4": "sibling, friend, boy, girl, brother, sister, happy, group, family",
  "CQHn-NvuheYkssXN0XX1f556T4Qw642DUSzxxFh5ksA": "night, moon, mountain, sky, star, cloud",
  "eozR8ErubUK4eDCyQ83QaV8oiUoc998J2cOOM0uN5IE": "4, four, heart, love, emotion",
  "gnSJtNS2pT9RkeV2FT2Pjy3c6ctCpz3VD0bYtsGF6-U": "telephone, phone, call, ring",
  "wo60xi3jhfXJ6xWiVxgfJOoOLaVzmm2GM_ykeuqr6fs": "bed, sleep, rest, bedroom, tired",
  "ClpS6wAWCQX5NlJVBYa-X4rPwrBybTJ99QTbKvgtsuM": "shell, conch, beach, ocean, sea, spiral",
  "17E-M2ZF25qT1pNgOMphVqQRYX_7J81tNBRwPSLNkjY": "piano, grand, music, instrument, play",
  "k-Zvt0OHmexn8gT3aUA8L3wKkstblIfqwD6OWwF7Lzw": "balloon, red, party, birthday",
  "3B6jVK596TWqKObwZ1_m5SYeyovQEtwJ_kjcZdfELXk": "baseball, ball, sport",
  "BxJiEF8yUYxcIY2FKUJrPhM1gFdjZnUYWK9JEPhmQuk": "basketball, ball, sport",
  "izNRdbPouF5t5_M7A3NzSSIBL3ZUytSOJcv72jp1qSg": "ornament, christmas, holiday, decoration",
  "8ScBWA1nFrl753Bz4nz6QrixJ86_cy6xYsQIsTaatI4": "ornament, christmas, holiday, decoration",
  "xIwUGj8g-eWBFj9QPXc2PxSpjoON3faqRXs87A1-AeY": "alien, ufo, space, martian, extraterrestrial, ET, space, invaders, game, arcade, pixel",
  "nfHVQDvE86dli-ST_XmX1AA54F6kd4fY3ZZMDYONAys": "shirt, blue, tshirt, clothes",
  "CPVyTz94BbdoKpVoHFSwVTiFmLQuwM_cc1VAK4V5w_Y": "bowling, ball, sport",
  "6CDyFMtDHZiWGDopsMqcpZyWX5TyLvVcTI8BhCMSRxc": "medal, gold, winner, award, prize, trophy",
  "89rCDsmg8YVen_pIx3LO9LUwXWwfgPARkoJXtTLb0ag": "paint, brush, paintbrush, art, draw",
  "ZD1Xdz_jM9wKmFNoVWruddwdvMjTE7mZhzy0_LjsXE0": "candle, flame, fire, light",
  "91hyKUIwhCjgJHFBWMN1epMhUQgimiGvcwxHmdPSiUs": "taperecorder, record, cassette, music, play",
  "azGC3Oq_2H1GAstSRd8mQkZsptogKU4eV3XcjNytxg4": "cassette, green, tape, music, play",
  "9w8bkuGKN9Ja26lRdoNapbNMTB3tBArkj7PnLTv8P8k": "chair, table, seat, furniture",
  "LnQiHW-v-7y6_hYNm-ejZ-2ZkkMwXqfeRfZrdsIXoT0": "chair, armchair, seat, furniture",
  "0wsZH465oWs1TH3M22FWphL3e00AbaonJUkto38SDHQ": "eye, eyeball, look, watch, see, spooky, halloween, scary",
  "W7t2STPQIhqNVQcX1ENAp7iaRF7hgYockKZKYzeNHew": "medal, gold, winner, award, prize, trophy",
  "5vd3fVcbFGXhsTjJJcCgU3Nkhd4y0FKxseJj00-2P1E": "graduate, cap, hat, diploma, degree, education, learn, school",
  "GtqHRkUstg4DOioMDBEWy1sulJWLyvUgoaSSCr1Kpac": "frog, alien, ufo, space, martian, extraterrestrial, ET, space, invaders, game, arcade, pixel",
  "okPV-hUhJdVUmkJnaxdrcIEomMYzhK1SSzuFZxuebpE": "glasses, spectacles, eyesight, vision, see",
  "0Itru93LwOy2xTEDs0eEm__pWZWAUgdbOhifIWQsKSw": "crown, king, queen, prince, princess, royal, kingdom, medieval",
  "H0K_gfR_okOaT3bsVqYOpr4IlxD0HYPdoWPHaEKlW9c": "lightbulb, light, bulb, idea, think, solution, bright, electricity",
  "aYZuAy1tBXz1jvgLLKu9lmDKizv3Pu8WSdwxsGa1JXw": "gift, present, birthday, christmas, bow, ribbon",
  "Iy-nPpe_apDwYTUX1UzG1rTS8pM8Kgp0_tX4z7jrZM8": "trophy, prize, award, winner, contest",
  "Rrj9ZSZonatOL5Li8qrWo97qPIVTziQz5FqnQ8nEz6M": "key, lock, secure, safe",
  "mnhKxVAigT1Io7UgVbMsNhzkFMST_7fJ4b_OJLYaCD8": "key, lock, secure, safe",
  "b5ueMXTsPO3WMQZXDwACWJx0t7_UyFOEPAd5NI5LHWo": "keyboard, piano, music, instrument, play",
  "96vj6NNbs25YDHJ38Wr93fpQd8QO1oWUWpeBBiOYh4k": "magnifyingglass, magnify, glass, zoom, search, find, detective, mystery",
  "JWynyloR5QeGMdlyEJzIMypkmaLY_1D8zffkfxB639Y": "microphone, music, sing, sound, voice",
  "rLkfL56rlXnnZGMcgAactFiZZ_1p40uJeh2KwJD4edU": "paint, brush, paintbrush, art, draw, construction",
  "yq0FFu9jdZ7dLXW4AYTKxw1XEwF-YkTeWQyNMrBuc-U": "flute, panflute, music, instrument, play",
  "osWQENoZbnPRNPjX5zMksi-lSrYDRRjPWuDUIH9azL4": "tada, celebrate, party, birthday",
  "j6YrT0YDwgvFv9WoTe3DlNiq9ubSjWHNT566LRaEUIA": "pencil, write, draw, school, study, writing",
  "q39cC7SW1Ku-AhD6G3Kqu5q3ifM65_kGVjyK_TPNBmo": "pencil, write, draw, school, study, paper, writing",
  "juZwjkVNrvSWs30zvV4Wpbg4YCZIXLV5cmms-tgx_Fs": "pencil, write, draw, school, study, paper, writing",
  "0pP_hRxUrwNGK9wZfIlB42xOH4BSIM2gsPF4tvAkFFc": "pencil, paintbrush, paint, draw, write, school, writing",
  "1Vr-Bf83yWfbimcQebL08Ns5ll2h0h4QQFd11X7UJt8": "piano, music, instrument, play",
  "-tBU__hJe4i9GzpNdLKoXWDi6FHqgw2CfqFboCJ86RQ": "chemistry, science, potion, experiment, magic, wizard",
  "A_xkm5MKnsIcOe_rNT-cxgEG3fX0vGVcVhAvib6_Lw0": "chemistry, science, potion, experiment, magic, wizard",
  "8Lp7lzhrxYOoOgwXV6HV3y7A6ufPvx789IZPff7EEqA": "chemistry, science, potion, experiment, magic, wizard",
  "1a7B1XcR1krHWYERgxQWj_taijM6zwgfXzj9d8w6Ri4": "present, gift, birthday, christmas, bow, ribbon",
  "eAi01fJ5Tzou-a-8N_seHiFkC_OU4wP2ajs8pBei5gQ": "present, gift, birthday, christmas, bow, ribbon",
  "j5Zsb_1tTH_cPx-i_ssdEIkxOEwqZijegToGfoIhWQU": "shirt, purple, tshirt, clothes",
  "yl4cJm6MNNh2Ygui0-feL9Cbi5QdxjSHaoDsK8vCnNk": "record, vinyl, music, album, LP, play",
  "Br1tU_aOMnhL2zrnZVoO29poxVpi8G26XvAAsNZWQ4g": "octopus, alien, ufo, space, martian, extraterrestrial, ET, space, invaders, game, arcade, pixel",
  "XABA6k_7MXJhxcUMXHXZSuhG5lWx8hKCQYYhbJG_fJ4": "glasses, spectacles, eyesight, vision, see",
  "mRY1W2bvpdjeZy_U93q7bK7nGEubqNgbFfvvmwkViGA": "umbrella, red, rain, weather, spring",
  "KJvBxz2x1IaD6Aw9cdmM49JX31SWtkSDnySn6FsZajU": "saxophone, music, instrument, jazz, play",
  "-PTird3Fjwr8ScCpMQALkiNl2ogL1Q6aic7aituHOqw": "medal, silver, second, winner, award, prize, trophy",
  "rSpJXU1KiFyRCyUT5i-4IIe16RIljTSXaAKhDjnFI1M": "sleigh, santa, christmas, sled, snow",
  "1BmICpZq6EcyV3ETmcnsgIQNrRsIkMeBfsGqAHQXAds": "stocking, santa, christmas, gift, sock, foot, feet",
  "h_L6-T4JtDr2_xV-y1f1Y6t4b6453rif51hoRObWKd4": "stocking, santa, christmas, gift, sock, foot, feet",
  "s5dvnrpcxLdGqY34zWsjI695lMDUmyJR9fFx34-B8to": "shoe, running, run, sport, sneaker",
  "h81EDdy1Gj7UX-1i930-8zhQBURzS7TveFw3L-MDDSc": "radio, computer, machine",
  "UdOGC-LBl6ytpA5PrtFkoevbSv-jkQa_pjlkvZ3RJlM": "chest, treasure, pirate, gold, rich",
  "uZqrOkH8R_o9QAn7-vRajGU_erp2uGf0FJ3kiatJ-mo": "violin, viola, music, instrument, play",
  "t3cdqUfsyZ6nn9dYFenK71yT_n5wbsGe39WaNyk1cHc": "cane, walking, stick, crook, hook",
  "PVIwpXl57MKiYBzIrLQJMex0YVR9L4HAaZD-I4KFj10": "wash, washing, machine, clothes, laundry",
  "HCrpU-uv0x919SFhhOw3S8uznG8b4CuXZVMSHMldNXU": "wheelbarrow, garden, carry",
  "56jeIPuqOFdmGAZlFHoyHFozZ8RAk-MtUc9iWrstCzM": "xylophone, music, instrument, play",
  "PpT-9U7kRkK_DzIJYVR7x42AGlF516WCi1zoSHuSseU": "alien, ufo, space, martian, extraterrestrial, ET, space, invaders, game, arcade, pixel",
  "swGiQoY6S6QAIbEkG-VL14AFQYPYMkFY094GO7r1CGk": "jacket, rain, yellow, coat, clothes, shirt",
  "mK3HNIpyYnhz2Yp5RPhLXLKOiRWHSAwxFrMQmh9XYus": "sun, ocean, sea, summer, vacation, beach",
  "Duh2XEMie_afQaQZOqW1wFTrA63A8WvxCZBqsdxckCk": "narwhal, underwater, ocean, sea, whale",
  "-acm43G-y4HPWCb9nI6XEyeOqwe0xmOBUvqU6-Ja5ts": "kangaroo, animal, jump, hop, australia",
  "MI8Nsr8JwYyQiTobd4Rscp0ZBYuumE-w_bEpGkWBdac": "medal, gold, winner, award, prize, trophy",
  "Y6EEmxbznOKuMlebez7Pg8ZmG944b58uauCRiBWoBTs": "compass, direction, north, south, east, west, pirate, treasure",
  "B_ghU_mVfDmvBqNKZq5CjiEF5ESq5WlVsT7NDELTSEA": "witch, hat, halloween, costume, wizard",
  "7kMWwjZQUrn61Ac1JnLz7cJH6JW0I4vQGBOgD72M6Eo": "lightning, thunder, storm, weather",
  "Dpn0ikOcXBRkf49Ic4-L3NV0rFLrcS89e2y8bVIs9KM": "cat, mask, japan, animal",
  "193C5alsvJtYSjnEqKY9ZP7xwar9cCJDv54BrozYGOA": "broom, mop, clean, sweep",
  "lA8ooFcsr-ngx-lmrQxqmFe4fXhOXTJ0tP4vyk7vuQY": "drum, music, instrument, play",
  "Amz2k-VVDTaYHBWt9aCzWMGFZoowtTfrK2mfX2CvkII": "drum, music, instrument, play",
  "W6rqhMLpt_mmmMvZFU9bucKJhgedvbnfQ5ExjTiP3DA": "guitar, electric, rock, jazz, music, instrument, play",
  "GIjMKBVV6LjGob6PfKM5x0CvBgl3IEZ4GXy1cXpLsqE": "guitar, jazz, music, instrument, play",
  "B-8c9ZMvTXTRmDdID5moqJ_8P7yadtTmmTGUEwQ-kZY": "cupcake, hat, winter, cold, snow, dessert",
  "L1aKXH8qNtQW63MjF5RVXpNUhUwfNaD0A1YEvAjRZ0A": "hand, heart, love, hold",
  "py375qmDkqVe1SGfG1DirF85A7YVPnEEK7ypvP2Xpbk": "bowl, bowling, ball, pin, sport",
  "X70J6YyOmWpPw4q2OSWZVGAilzBXWNPXhB3alpOHV_k": "tennis, ball, sport",
  "o3BHfsLMF7qN3_4p3EjzuWrM6BDV4aEx6GFl8Kuxpeg": "ball, sport",
  "4JhcJ3T4qblyWoS-mnV1qSx64DSBHd25Hp00ja7c-IM": "bee, bumblebee, buzz, insect, bug, animal",
  "I5B8p0HYRhwFq5apZWW0hqvfX_JPhoLUJ1n4zGoBekM": "ladybug, ladybird, insect, bug, animal",
  "4yNf9V9JF81hsMJ8JbJQzRomM0MnGopc33LwSMd8qNk": "music, note, sound, listen, hear, sing, song",
  "RJom4iDawMiytsMMbskLufea6688PVN3FqsVWd3-qA4": "volcano, lava, magma, erupt, mountain",
  "Vu4lpBBXYpOxVynT9YHakTTnLbKMywGPpO8-4Me1cGE": "cloud, rainbow, happy, sky, weather",
  "aG-BgnJ1Rc38ax9ikcc-XW3d2j-U2DHQGm3FpnCbzzs": "star, happy, sky, night, space",
  "IO32NRx4ndXmyGtWTyftIhPgKY9Df9CN1Gv-F8tuU0E": "star, sky, night, space",
  "_7CzVIVcBy2D_K-A0Sn4MHlaykP1sd0y7NmGdPTccl0": "star, sky, night, space",
  "lS8lRmfOVjBQ6m2n7w8yRsBGiUt2Cfc1-Br41yNAZMA": "star, sky, night, space, shoot",
  "aMfVApov1X4mAmNqsDRk8-DNlWcFrlR_ISUUUC9iLdk": "tulip, orange, pink, yellow, flower, plant",
  "VpDy5f9vMyAv6dYe-cZ28wGzCfcDWYh2_DRO3zE66nw": "ocean, wave, sea, water, beach, vacation",
  "LFGuO-YB89xPlqIoQqs06t2JlhhBPAqq05oEhlGPuY8": "earth, globe, world, planet, smile, happy",
  "ZFQJn8jgKCRl5H8tG_P5IM63JF2fK9t84yeI3NhFSFw": "ear, hear, listen, sound, body",
  "VxLL1lqSfYfWBvvrdFqbhlPiI3N2T-MHMrT8T8aRaTE": "building, apartment, office, city, house, clock, tower, england, europe, travel, vacation",
  "FhuY59vo70O7dVOTKucVt47VBgK9Kf_ZIuExmkUxIGU": "rain, snow, hail, weather, cold, winter, storm",
  "Hg0vhp0es_CmMrku0MSRJBIfjhLv3ZkFpJEcnzmhcfw": "skull, bones, skeleton, halloween, dead, scary, spooky",
  "6MuxudYzgak_gqKJW1vyMfL3PV7eivMi__9rWuElGJY": "heart, envelope, love, letter, valentine, emotion",
  "Y8BqWsxnRldYVBlCzszwJio5QF7Nk7QSMjm5alrqcfA": "3, three, crayon, draw, write, school, writing",
  "BWxITAgCaaJ7Iidau0P8cr0znqZTANriShU_ZfDwCmQ": "leaf, green, nature, tree, plant, fall, autumn",
  "3jjRmjCbJuELt3lyNMFlEZTmcr6uHbLcsjiG9SJSImY": "leaf, brown, nature, tree, plant, fall, autumn",
  "0w3kLGtL2XqWTJqPJZJU8ojkL3R8dmeGBdbbYAd9oWc": "bouquet, flower, plant, gift, valentine, prize, celebrate",
  "ZLg3VGQdvyGhjRFonskHA-LXSs99PHQ5iW7nWV0L9YE": "christmas, tree, holiday, winter, snow, pine",
  "BeRPRrYDkvCWcipf_gf8f5t6foMa1m5ISCpgazq9SOI": "tree, nature, plant, forest, wood",
  "kIxagO8MDh8ivEtcWIv7JyDRoD6my0KtzWtvlrNwVSU": "clover, leaf, plant, nature, luck, irish",
  "gQZ_fZRjrz_tjkC5xuaFosmsJi3Qi5MHky_b3mSAydY": "paris, eiffel, tower, france, europe, travel, vacation",
  "L391XuT0Yb1qFTCP6POgb4T0bE2iPmuHk5lkOeCX3bU": "dinosaur, dragon, trex, reptile, animal",
  "uE3qAf16H1tYVYgbu2kgOTldcLLfFarPLlZsZ9I9wOo": "camp, fire, marshmallow, smore, summer, vacation, hot, flame, burn",
  "pte3JPzKk5dbX4mGocsgoz6r9Q3yqU_dLcWsmOYclbc": "santa, claus, christmas, holiday, beard, december",
  "09DQgICpkT6gPwG-0DFb0W4Y5NhrlOx2e_L3nLOHzpk": "boot, shoe, foot, winter, cold, snow",
  "1LW3F1TV6CX_iWx-r41QWbiAd330G4UHUEv4yiugpB4": "run, sneaker, shoe, sport, foot",
  "n5oVvoU4OIGlbR_UpAVECjqv9HHIRBnF-nscIXWCC10": "bone, dog, skeleton, pet",
  "2oIJ5dJDp249P1m1uzGh5xAJ6RggBhU_riydZIlvtrA": "bear, teddy, toy, animal, stuffed",
  "hf-1JhGYXLBkNOKhY02EQ9wv5uvjKC_B4gv3uyd14Z4": "holly, christmas, holiday, plant, winter",
  "kXqjkIHLm-Gmp0H8iwsiMI3CWG3_AXnYDvN4ib1kzbI": "shell, conch, beach, ocean, sea, spiral",
  "mlWc6s-JGfZcFBP44Ok9xDBUANWQlBOOckHh44f06pg": "bag, purse, red, fashion, clothes",
  "7Wt--qhx9t7PCSC8WBmGKJvlG53Z1uk7bN1dE9wGWJ0": "plant, sprout, pot, flower, grow, nature"
}
